//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.VoucherDetail = new HashSet<VoucherDetail>();
            this.BillDetail = new HashSet<BillDetail>();
        }
    
        public int BillId { get; set; }
        public string Code { get; set; }
        public decimal TotalAmount { get; set; }
        public int Quantity { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Modifiedby { get; set; }
        public int TypePayment { get; set; }
        public Nullable<bool> Confirm { get; set; }
        public Nullable<bool> TypeReturn { get; set; }
        public Nullable<bool> Success { get; set; }
        public Nullable<System.DateTime> SuccessDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherDetail> VoucherDetail { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetail { get; set; }
    }
}
