//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.ImportWarehouse = new HashSet<ImportWarehouse>();
            this.Invoice = new HashSet<Invoice>();
            this.Role = new HashSet<Role>();
        }
    
        public int EmployeeId { get; set; }
        public string PhoneNumber { get; set; }
        public string NameEmployee { get; set; }
        public string CitizenIdentificationCard { get; set; }
        public string Email { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Location { get; set; }
        public decimal Wage { get; set; }
        public string Sex { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> FunctionId { get; set; }
        public string Image { get; set; }
    
        public virtual AccountEmployee AccountEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportWarehouse> ImportWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Role { get; set; }
        public virtual tb_Function tb_Function { get; set; }
    }
}
