//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceDetailId { get; set; }
        public int InvoiceId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public int ProductDetailId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
