//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProductDetailId { get; set; }
    
        public virtual OrderCustomer OrderCustomer { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
