//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductDetail = new HashSet<ProductDetail>();
            this.Review = new HashSet<Review>();
        }
    
        public int ProductsId { get; set; }
        public string Title { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Modifiedby { get; set; }
        public string Alias { get; set; }
        public Nullable<int> Screensize { get; set; }
        public string CPUspeed { get; set; }
        public string OperatingSystem { get; set; }
        public string GPUspeed { get; set; }
        public string MobileNetwork { get; set; }
        public string Sim { get; set; }
        public string Wifi { get; set; }
        public string GPS { get; set; }
        public string Bluetooth { get; set; }
        public string Connector { get; set; }
        public string BatteryType { get; set; }
        public string ChargingSupport { get; set; }
        public string BatteryTechnology { get; set; }
        public string Image { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public Nullable<int> BatteryCapacity { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductCompanyId { get; set; }
        public string Description { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductCompany ProductCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Review { get; set; }
    }
}
