//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Modifiedby { get; set; }
        public string Content { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public int Ratingscore { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Products Products { get; set; }
    }
}
