//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherDetail
    {
        public int VoucherDetailId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public Nullable<int> BillId { get; set; }
        public Nullable<int> VoucherId { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
